apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.claimName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "photos-pv.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  volumeName: {{ include "photos-pv.fullname" . }}-pv
