apiVersion: v1
kind: Secret
metadata:
  name: {{ include "photosearch-postgres.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "photosearch-postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
