apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "photosearch-api.fullname" . }}-photos-pv
  labels:
    {{- include "photosearch-api.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.photosNfs.storageClass }}
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: {{ .Values.photosNfs.size }}
  accessModes:
    - ReadOnlyMany
  nfs:
    server: {{ .Values.photosNfs.server }}
    path: {{ .Values.photosNfs.path }}
    readOnly: true
