apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "photosearch-api.fullname" . }}-photos-pvc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "photosearch-api.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.photosNfs.storageClass }}
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.photosNfs.size }}
  volumeName: {{ include "photosearch-api.fullname" . }}-photos-pv
